[package]
name = "bench-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
rollup-core = { path = "../rollup-core" }
tokio = { version = "1", features = ["full"] }
rand = "0.9.2"
indicatif = "0.18"
bincode="1"
rocksdb = "0.24"